{ pkgs, ... }:
{
  home.packages = with pkgs; [
    fastfetch
    pavucontrol
    git
    gh
    wget 
    unzip
    unrar
    materialgram
    #telegram-desktop
    xdg-utils
    imv
    #mpv
    celluloid
    hyprpicker
    rofi-wayland
    qbittorrent
    (pkgs.btop.override { cudaSupport = true; })
    veracrypt
    swww
    clipman
    #waybar
    hyprshot
    grim
    hyprpicker
    vscodium
    discord
    nautilus
    #nemo
    #gnome-tweaks
    gpu-screen-recorder-gtk
    #spotify
    #spicetify-cli
    wl-clipboard
    cliphist
    xclip
    gnome-disk-utility
    ntfs3g
    xdragon
    pywal
    rewaita
    mangohud
    goverlay
    gamemode
    ranger
    brightnessctl
    pulseaudio
    swaynotificationcenter
    obs-studio
    #oh-my-fish
    #gimp
    onlyoffice-bin
    onefetch
    tokei
    prismlauncher
    fzf
    clipse
    xwayland-satellite
    #nvtopPackages.full
    libnotify
    gsimplecal
  ];
}