{ pkgs, ... }:
{
  home.packages = with pkgs; [
    fastfetch
    pavucontrol
    git
    gh
    wget 
    unzip
    unrar
    materialgram
    xdg-utils
    imv
    mpv
    #celluloid
    hyprpicker
    rofi-wayland
    qbittorrent
    (pkgs.btop.override { cudaSupport = true; })
    veracrypt
    swww
    clipman
    hyprshot
    grim
    hyprpicker
    vscodium
    discord
    nautilus
    gpu-screen-recorder-gtk
    wl-clipboard
    cliphist
    xclip
    gnome-disk-utility
    ntfs3g
    xdragon
    pywal
    rewaita
    mangohud
    goverlay
    gamemode
    ranger
    brightnessctl
    pulseaudio
    swaynotificationcenter
    obs-studio
    onlyoffice-bin
    onefetch
    tokei
    prismlauncher
    fzf
    clipse
    xwayland-satellite
    libnotify
    gsimplecal
  ];
}