# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "uas" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4804d829-7f68-4140-8e1d-29e63ee57407";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CEF1-8965";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };


  fileSystems."/mnt/bine4" = 
   { device = "/dev/disk/by-uuid/5896645a-9e7f-4846-a1d3-1625ef22fd30";
      fsType = "ext4";
      options = [  "nosuid" "nodev" "nofail" ];
   };

  fileSystems."/mnt/bineM" = 
   { device = "/dev/disk/by-uuid/cff08dd0-0c9d-4988-beb6-c72f7e93d912";
      fsType = "ext4";
      options = [  "nosuid" "nodev" "nofail" ];
   };

  fileSystems. "/mnt/bine2" =
    { device = "/dev/disk/by-uuid/cbcab1b2-db82-4220-9376-0d881d56c5ca";
      fsType = "ext4";
      options = [ "nosuid" "nodev" "nofail" ];
   };
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp82s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
